export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_CONTACTS_PENDING = 'REQUEST_CONTACTS_PENDING';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS';
export const REQUEST_CONTACTS_FAILED = 'REQUEST_CONTACTS_FAILED';